// Re-export validation helpers from a single module so callers don't need to
// know which file they live in. Round-robin generation in JS is no longer
// needed because matches are generated by the app_generate_round_robin_matches
// RPC, but we keep the JS implementation as a pure helper for tests and any
// preview UI we might want later.

export {
  normalizeWhatsAppUrl,
  validateTournamentName,
  validateTournamentFormat,
  validatePlayerName,
  validateEmail,
  validateOptionalEmail,
  validatePassword,
  validatePlayerCount,
  validateWhatsAppUrl,
  validateMatchScore,
} from '@/lib/validation';

export type GeneratedMatchDraft = {
  round_label: string;
  court_label: string;
  team_a_label: string;
  team_b_label: string;
};

export function generateRoundRobinDrafts(
  playerNames: string[],
  courtCount = 4,
): GeneratedMatchDraft[] {
  const cleaned = playerNames.map((p) => p.trim()).filter(Boolean);
  if (cleaned.length < 2) return [];

  const drafts: GeneratedMatchDraft[] = [];
  const courts = Math.max(1, Math.min(16, courtCount));

  for (let i = 0; i < cleaned.length; i += 1) {
    for (let j = i + 1; j < cleaned.length; j += 1) {
      const idx = drafts.length;
      drafts.push({
        round_label: `Round ${Math.floor(idx / courts) + 1}`,
        court_label: `Court ${(idx % courts) + 1}`,
        team_a_label: cleaned[i],
        team_b_label: cleaned[j],
      });
    }
  }
  return drafts;
}
